### ISSUE TITLE
add "apiUrl" and "wsUrl" options

### ISSUE THREAD

**Issue by maozedong** [bitvavo/node-bitvavo-api#2]
Hi! Thanks for useful api client! It saves a lot of time

One part is missing currently - it's useful to be able to set custom rest and ws api urls. For example it can be used in integration tests. It's a common scenario to create mocking server on `localhost` and use it with tests.

Options like this can be very useful
```javascript
const bitvavo = require('bitvavo')().options({
  restUrl: 'http://localhost:8080'
  wsUrl: 'ws://localhost:8081'
})
```

**Comment by joeri-vv** [comment]
We've updated all SDK's to include this option, restUrl and wsUrl can now both be set through the options function.
