### ISSUE TITLE
Ability to disconnect from websockets

### ISSUE THREAD

**Issue by maozedong** [bitvavo/node-bitvavo-api#3]
Currently when ws connection is established bitvavo will try to reconnect whenever it receives "close" event. So no way to disconnect for client app. Something like `bitvavo.websocket.disconnect()` will be very helpful. `disconnect` method should also probably cleanup eventListeners

code sample to illustrate the issue
```javascript
const b = require('bitvavo')();

(async () => {
  await b.websocket.subscriptionTrades('BTC-EUR')
  b.websocket.websocket.close() // no way to really close ws connection
  setTimeout(() => {
    console.log(b.websocket.websocket.readyState) // readyState == OPEN again
  }, 1000)
})()
```

**Comment by joeri-vv** [comment]
We've updated the SDK with a close() function. The example you provided now functions as it should:
const b = require('bitvavo')();

(async () => {
  await b.websocket.subscriptionTrades('BTC-EUR')
  b.websocket.close()
  setTimeout(() => {
    console.log(b.websocket.websocket.readyState) // now prints 3 instead of 1
  }, 1000)
})()

Cleaning the eventEmitter can be done through emitter.removeAllListeners() . But the emitter will persist when opening a new socket, so it can be kept intact as well.
