### ISSUE TITLE
Market data JSON numbers are serialized as strings

### ISSUE THREAD

**Issue by quixot1c** [bitvavo/node-bitvavo-api#6]
All numbers that are returned from the API are serialized in the JSON as strings. This is very inconvenient if you want to do some computation on these numbers, because you need to first `parseFloat()` or `Number()` all of them before you can do this. If you would serialize the numbers as JSON numbers, the `JSON.parse()` that you probably do will automatically rehydrate the numbers as actual usable numbers. I.e:

```
[1.3333, 50000]
```
instead of
```
["1.333", "50000"]
```

**Comment by bakman2** [comment]
Temp quick solution:

```
let response = await bitvavo.tickerPrice({})
response.forEach((x)=>{x.price=Number(x.price)});
```

**Comment by quixot1c** [comment]
Yes, better still to use `Array.prototype.map` instead of `forEach` but the point is that there is quite a lot of data coming in multiple times per second when using Websocket connections and having to loop over all the data just to first turn it into numbers is just wasteful. I want to build an interface that works with Bitvavo that runs at 60 fps and updates a lot of UI on every socket update (just like the advanced interface of Bitvavo) so every millisecond counts. The API should deliver numbers as JSON numbers so `JSON.parse()` that is used inside the code that handles the response in the client code of this repo immediately turns the JSON into numbers in memory.

**Comment by joeri-vv** [comment]
All numbers are returned as string to preserve precision. As this is also not due to this SDK, but the API itself i will close this issue.
