### ISSUE TITLE
Missing unsubscribe actions for websocket connections

### ISSUE THREAD

**Issue by quixot1c** [bitvavo/node-bitvavo-api#7]
When inspecting what the Bitvavo client does on Chrome I saw that it fires `ubsubscribe` actions in certain instances. However, these actions are missing from `node-bitvavo-api`.

**Comment by joeri-vv** [comment]
You are correct, we might implement this feature later. For now you can extend the SDK yourself by copying the subscribe message from the appropriate functions and replacing the 'subscribe' action with 'unsubscribe'.

**Comment by the-serious-programmer** [comment]
https://www.npmjs.com/package/bitvavo-fork/v/1.2.1 - a quick solution is published here

**Comment by ca42rico** [comment]
Fixed in [PR 23](https://github.com/bitvavo/node-bitvavo-api/pull/23)
Thanks to @the-serious-programmer
