### ISSUE TITLE
No webbrowser support

### ISSUE THREAD

**Issue by quixot1c** [bitvavo/node-bitvavo-api#8]
It would be very nice if the code that is in this repository could also be used in a webbrowser environment. `node-bitvavo-api` however fails because it uses `require('ws')` and a difference in how `this` is handled between `node` and `browser` environments. 

I managed to make the code work by removing `const WebSocket = require('ws')` and changing `this.reconnectTimer` etc to:
```
let reconnectTimer = 100;
let authenticated;
let websocket;
let websocketObject;
```
Hopefully you can make it work on browsers without modifications for the end user, making the api available to a broader audience with minimal changes to your code.

**Comment by joeri-vv** [comment]
Since this SDK was designed for NodeJS we did not implement functionality for browser. Ofcourse feel free to implement this for yourself.
