### ISSUE TITLE
API produces rounded price for BTC-EUR ?

### ISSUE THREAD

**Issue by bakman2** [bitvavo/node-bitvavo-api#9]
Perhaps not directly related to this code, not sure, but the output of:

```
try {
  let response = await bitvavo.tickerPrice({})
  for (let entry of response) {
    console.log(entry)
  }
} catch (error) {
  console.log(error)
}
``` 
always includes BTC-EUR with a rounded number (your example output actually shows a floating however).
Is there a specific reason for this ?

**Comment by joeri-vv** [comment]
The price is returned with a precision of 5. Since BTC-EUR now has passed 10.000, we no longer return floating point for BTC-EUR. If the price will fall below 10k again, we will return the price with 1 decimal.
